name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Chrome
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: pnpm dev
          wait-on: "http://[::1]:5173"
          wait-on-timeout: 200
          browser: chrome

      - name: Edge
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: pnpm dev
          wait-on: "http://[::1]:5173"
          wait-on-timeout: 200
          browser: edge
